//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Attendance.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No questionnaires selected!.
        /// </summary>
        public static string Export_NoQuestionnaireSelected {
            get {
                return ResourceManager.GetString("Export_NoQuestionnaireSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire was transferred already..
        /// </summary>
        public static string Export_QuestionnaireAlready {
            get {
                return ResourceManager.GetString("Export_QuestionnaireAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire was removed..
        /// </summary>
        public static string Export_QuestionnaireRemoved {
            get {
                return ResourceManager.GetString("Export_QuestionnaireRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire was transferred successfully..
        /// </summary>
        public static string Export_QuestionnaireTranferred {
            get {
                return ResourceManager.GetString("Export_QuestionnaireTranferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attendances selected!.
        /// </summary>
        public static string Import_NoAttendanceSelected {
            get {
                return ResourceManager.GetString("Import_NoAttendanceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire was imported already..
        /// </summary>
        public static string Import_QuestionnaireAlready {
            get {
                return ResourceManager.GetString("Import_QuestionnaireAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire was imported successfully..
        /// </summary>
        public static string Import_QuestionnaireImported {
            get {
                return ResourceManager.GetString("Import_QuestionnaireImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logged in user doesn&apos;t have the right for importing this sdf file ! .
        /// </summary>
        public static string Import_QuestionnaireNotAuthorized {
            get {
                return ResourceManager.GetString("Import_QuestionnaireNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire was removed..
        /// </summary>
        public static string Import_QuestionnaireRemoved {
            get {
                return ResourceManager.GetString("Import_QuestionnaireRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database file was uploaded successfully..
        /// </summary>
        public static string Import_UploadFileSucceeded {
            get {
                return ResourceManager.GetString("Import_UploadFileSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect!.
        /// </summary>
        public static string Login_PasswordIncorrect {
            get {
                return ResourceManager.GetString("Login_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exiting!.
        /// </summary>
        public static string Login_UserNotExist {
            get {
                return ResourceManager.GetString("Login_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected question deleted successfully..
        /// </summary>
        public static string QuestionPool_DeleteSucceeded {
            get {
                return ResourceManager.GetString("QuestionPool_DeleteSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected question duplicated successfully..
        /// </summary>
        public static string QuestionPool_DuplicateSucceeded {
            get {
                return ResourceManager.GetString("QuestionPool_DuplicateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Attendance was transferred successfully..
        /// </summary>
        public static string TransferToDatabaseSucceeded {
            get {
                return ResourceManager.GetString("TransferToDatabaseSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment file deleted successfully..
        /// </summary>
        public static string Vetting_DeleteCommentSucceeded {
            get {
                return ResourceManager.GetString("Vetting_DeleteCommentSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carried out status updated successfully..
        /// </summary>
        public static string Vetting_UpdateCarriedOutStatusSucceeded {
            get {
                return ResourceManager.GetString("Vetting_UpdateCarriedOutStatusSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment updated successfully..
        /// </summary>
        public static string Vetting_UpdateCommentSucceeded1 {
            get {
                return ResourceManager.GetString("Vetting_UpdateCommentSucceeded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status updated successfully..
        /// </summary>
        public static string Vetting_UpdateStatusSucceeded {
            get {
                return ResourceManager.GetString("Vetting_UpdateStatusSucceeded", resourceCulture);
            }
        }        
        
        /// <summary>
        ///   Looks up a localized string similar to Status updated successfully..
        /// </summary>
        public static string Vetting_UpdateSucceeded {
            get {
                return ResourceManager.GetString("Vetting_UpdateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment file was uploaded successfully..
        /// </summary>
        public static string Vetting_UploadCommentSucceeded1 {
            get {
                return ResourceManager.GetString("Vetting_UploadCommentSucceeded1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is moved up successfully..
        /// </summary>
        public static string Viq__Edit_QuestionMovedUp {
            get {
                return ResourceManager.GetString("Viq__Edit_QuestionMovedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected category had already been added..
        /// </summary>
        public static string Viq_AlreadyAddedCategory {
            get {
                return ResourceManager.GetString("Viq_AlreadyAddedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected question had already been added..
        /// </summary>
        public static string Viq_AlreadyAddedQuestion {
            get {
                return ResourceManager.GetString("Viq_AlreadyAddedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected category is added successfully..
        /// </summary>
        public static string Viq_CategoryAddedSuccessfully {
            get {
                return ResourceManager.GetString("Viq_CategoryAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questionnaire duplicated successfully..
        /// </summary>
        public static string Viq_DuplicateSucceeded {
            get {
                return ResourceManager.GetString("Viq_DuplicateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is deleted successfully..
        /// </summary>
        public static string Viq_Edit_QuestionDeleted {
            get {
                return ResourceManager.GetString("Viq_Edit_QuestionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is moved down successfully..
        /// </summary>
        public static string Viq_Edit_QuestionMovedDown {
            get {
                return ResourceManager.GetString("Viq_Edit_QuestionMovedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected question is added successfully..
        /// </summary>
        public static string Viq_QuestionAddedSuccessfully {
            get {
                return ResourceManager.GetString("Viq_QuestionAddedSuccessfully", resourceCulture);
            }
        }

        public static string Observation_DeleteAttachmentSucceeded
        {
            get
            {
                return ResourceManager.GetString("Observation_DeleteAttachmentSucceeded", resourceCulture);
            }
        }
    }
}
