// <auto-generated />
using System;
using Attendance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Attendance.Infrastructure.Migrations
{
    [DbContext(typeof(AttendanceContext))]
    [Migration("20231009101352_UserIdentity")]
    partial class UserIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Attendance.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryNewID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Children")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Attendance.Models.InspectionTypes", b =>
                {
                    b.Property<int>("InspectionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InspectionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("bitReport")
                        .HasColumnType("bit");

                    b.HasKey("InspectionTypeId");

                    b.ToTable("InspectionTypes");
                });

            modelBuilder.Entity("Attendance.Models.QuestionPool", b =>
                {
                    b.Property<Guid>("questionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<Guid?>("CategoryNewID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Origin")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionTypeID")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questioncode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("questionid");

                    b.HasIndex("ParentId");

                    b.ToTable("QuestionPoolNew");
                });

            modelBuilder.Entity("Attendance.Models.QuestionType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("Attendance.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool?>("SignOff")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SignOffDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Attendance.Models.UserQuestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QId");

                    b.HasIndex("UserId", "QId")
                        .IsUnique()
                        .HasName("IX_UserQuestionnaire_User_Q");

                    b.ToTable("UserQuestionnaire");
                });

            modelBuilder.Entity("Attendance.Models.User_Roles", b =>
                {
                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("SystemRole")
                        .HasColumnType("bit");

                    b.ToTable("User_Roles");
                });

            modelBuilder.Entity("Attendance.Models.VIQ", b =>
                {
                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("Children")
                        .HasColumnType("int");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisplayIndex")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayLevel")
                        .HasColumnType("int");

                    b.Property<int?>("GlobalDisplayIndex")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InternalDisplayCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ObjectType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ParentType")
                        .HasColumnType("int");

                    b.Property<int>("QId")
                        .HasColumnType("int");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ShowAfterId")
                        .HasColumnType("int");

                    b.ToTable("VIQ");
                });

            modelBuilder.Entity("Attendance.Models.VIQInfoModel", b =>
                {
                    b.Property<int>("QId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Finalized")
                        .HasColumnType("tinyint");

                    b.Property<int?>("NumOfQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SecurityColumn")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VIQGUI")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.Property<string>("version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QId");

                    b.ToTable("VIQInfo");
                });

            modelBuilder.Entity("Attendance.Models.Vessel", b =>
                {
                    b.Property<int>("VesselId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("DeadWeight")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FleetId")
                        .HasColumnType("int");

                    b.Property<double?>("GrossTonage")
                        .HasColumnType("float");

                    b.Property<string>("IMO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Locked")
                        .HasColumnType("int");

                    b.Property<string>("VesselCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VesselId");

                    b.ToTable("Vessel");
                });

            modelBuilder.Entity("Attendance.Models.Vetting", b =>
                {
                    b.Property<int>("VETId")
                        .HasColumnType("int");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("AssigneeRank")
                        .HasColumnType("tinyint");

                    b.Property<int?>("VerifiedinVetting")
                        .HasColumnType("int");

                    b.Property<string>("answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("significance")
                        .HasColumnType("int");

                    b.HasKey("VETId", "ObjectId");

                    b.ToTable("Vetting");
                });

            modelBuilder.Entity("Attendance.Models.VettingAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VETId")
                        .HasColumnType("int");

                    b.Property<byte[]>("commentFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("commentFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VETId", "ObjectId");

                    b.ToTable("VettingAttachment");
                });

            modelBuilder.Entity("Attendance.Models.VettingInfo", b =>
                {
                    b.Property<int>("VetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Answered")
                        .HasColumnType("int");

                    b.Property<byte?>("CarriedOutStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyRepresentativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("InspectionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("InspectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectorSirName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MajorId")
                        .HasColumnType("int");

                    b.Property<int?>("Negative")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PortId")
                        .HasColumnType("int");

                    b.Property<int?>("Positive")
                        .HasColumnType("int");

                    b.Property<int>("QId")
                        .HasColumnType("int");

                    b.Property<string>("RegisterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VesselId")
                        .HasColumnType("int");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VetDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VetGUI")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VetTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VettingCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VetId");

                    b.HasIndex("InspectionTypeId");

                    b.ToTable("VettingInfo");
                });

            modelBuilder.Entity("Attendance.Models.QuestionPool", b =>
                {
                    b.HasOne("Attendance.Models.QuestionPool", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_QuestionPool_Parent")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Attendance.Models.UserQuestionnaire", b =>
                {
                    b.HasOne("Attendance.Models.VIQInfoModel", "VIQInfo")
                        .WithMany("UserQuestionnaires")
                        .HasForeignKey("QId")
                        .HasConstraintName("FK_UserQuestionnaire_Questionnaires")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Attendance.Models.User", "Users")
                        .WithMany("UserQuestionnaires")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserQuestionnaire_Users")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Attendance.Models.VettingAttachment", b =>
                {
                    b.HasOne("Attendance.Models.Vetting", "Vetting")
                        .WithMany("VettingAttachments")
                        .HasForeignKey("VETId", "ObjectId")
                        .HasConstraintName("FK_VettingAttachment_Vetting")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Attendance.Models.VettingInfo", b =>
                {
                    b.HasOne("Attendance.Models.InspectionTypes", "InspectionType")
                        .WithMany()
                        .HasForeignKey("InspectionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
